### ISSUE TITLE
Access Denied on generated video

### ISSUE THREAD

**Issue by MateuszSiek** [karelnagel/pulumi-remotion-lambda#11]
Thanks for continuing to develop the library! I've just tested the latest version. 
The multienv deployment seem to work perfectly but I'm not able to access the generated video so there might be something off with the permissions 🤔 

![CleanShot 2024-04-15 at 13 00 09@2x](https://github.com/karelnagel/remotion-sst/assets/16710005/f143ef9d-3bf1-4c68-8d8b-5bd803baf204)

Bellow if the screenshot of the permissions tab for the generated video, looks like its missing the public read permission.
![CleanShot 2024-04-15 at 13 03 54@2x](https://github.com/karelnagel/remotion-sst/assets/16710005/07a8850b-e5cd-45d7-8db4-50ba106153bb)

I'm using latest version(4.0.141) of remotion in case the permissions are on their side 🤔

**Comment by MateuszSiek** [comment]
Ok, please ignore it. I had `privacy: "no-acl",` set on `renderMediaOnLambda` 🙈 
![CleanShot 2024-04-15 at 13 13 25@2x](https://github.com/karelnagel/remotion-sst/assets/16710005/38941690-1223-49de-b20c-c40e27f8327a)

For some reason this was working just fine before. Commenting out that line fixes the issue 🙂

**Comment by karelnagel** [comment]
Glad it works for you! Yeah in the previous version the bucket had ACLs disabled and had all the files public, but since the remotion default deployment method uses ACLs, I changed this package to also use them and this way it's possible to make specific files public/private easily.
