### ISSUE TITLE
Auto delete renders

### ISSUE THREAD

**Issue by MateuszSiek** [karelnagel/pulumi-remotion-lambda#12]
Would be great to have the [auto-deletion](https://www.remotion.dev/docs/lambda/autodelete) work.

I guess every bucket could have those rules applied by default since it would only apply to renders that have a correct prefix.

I've prepared a PR enabling the rules on a bucket but I don't seem to have required permissions for this repo to push my changes.

**Comment by karelnagel** [comment]
Yes, that is a good feature. 
You can't directly push to here, but you can fork this repo, push code to your own fork and then create a PR from your fork to this repo.
