### ISSUE TITLE
403 Error on first deploy

### ISSUE THREAD

**Issue by karelnagel** [karelnagel/pulumi-remotion-lambda#4]
Only happens on first deploy the next one will be fine
```
  Failed
   Remotion pkg:index:RemotionLambda → RemotionBucketPolicy aws:s3:BucketPolicy
   Policy: operation error S3: PutBucketPolicy, https response error StatusCode: 403, RequestID: FB4Q37GN6RA95X45, HostID: Zfe3xgY1VhtB0SLvt/yiRU+5yJlMuphIQQk9MrCC34OfFUXJkK8Suq/cSO01DMMjsME8Gnm031c=, api error AccessDenied: Access Denied
```

**Comment by ryanleecode** [comment]
I got rid of this and made the bucket private on my end. my plan is to just change the output to a different bucket

**Comment by karelnagel** [comment]
but imo the bucket where all the remotion site files are should be publicly accessible for rendering to work

**Comment by ryanleecode** [comment]
> but imo the bucket where all the remotion site files are should be publicly accessible for rendering to work

Personally, Im keeping them separare b.c i dont want to leak the source code of how my renders are generated.

And it is an option:
https://www.remotion.dev/docs/lambda/custom-destination
